# Generated by Django 5.0.1 on 2024-04-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_estadio', models.CharField(blank=True, max_length=200, null=True)),
                ('preco', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Disponível'), (1, 'Reservado'), (2, 'Cancelado')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
